set(_CATKIN_CURRENT_PACKAGE "adc_raw")
set(adc_raw_VERSION "0.0.0")
set(adc_raw_MAINTAINER "pi <pi@todo.todo>")
set(adc_raw_PACKAGE_FORMAT "2")
set(adc_raw_BUILD_DEPENDS "rospy" "std_msgs" "message_generation")
set(adc_raw_BUILD_EXPORT_DEPENDS "rospy" "std_msgs")
set(adc_raw_BUILDTOOL_DEPENDS "catkin")
set(adc_raw_BUILDTOOL_EXPORT_DEPENDS )
set(adc_raw_EXEC_DEPENDS "message_runtime" "rospy" "std_msgs")
set(adc_raw_RUN_DEPENDS "message_runtime" "rospy" "std_msgs")
set(adc_raw_TEST_DEPENDS )
set(adc_raw_DOC_DEPENDS )
set(adc_raw_URL_WEBSITE "")
set(adc_raw_URL_BUGTRACKER "")
set(adc_raw_URL_REPOSITORY "")
set(adc_raw_DEPRECATED "")